### ISSUE TITLE
[BUG] The 'pypresence' distribution was not found

### ISSUE THREAD

**Issue by ZephaniahNoah** [RareDevs/Rare#209]
The AppImage actually runs fine. If I try to run the version installed with Rare-1.8.9.deb I get this:
```
zephaniahnoah@zephaniahnoah-pc:~$ rare
Traceback (most recent call last):
  File "/usr/bin/rare", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3254, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3237, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3266, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pypresence' distribution was not found and is required by Rare
```

**Comment by Dummerle** [comment]
I have no idea, what  is the error, but I will try to find the error. It must be an error with the generation of the deb file. As a workaround you can run `pip install pypresence` or if it won't work, `sudo pip install pypresence.

**Comment by ZephaniahNoah** [comment]
Yea I already tried that. It still can't find it.

**Comment by Dummerle** [comment]
You can try the latest deb file from Actions: https://github.com/Dummerle/Rare/actions/runs/2521938302

I will replace latest release file soon

**Comment by ZephaniahNoah** [comment]
![screenshot](https://user-images.githubusercontent.com/14168013/174502473-305c411f-f80a-4e79-abf3-f726c3a795c1.png)
```
zephaniahnoah@zephaniahnoah-pc:~/Downloads$ rare
QSocketNotifier: Can only be used with threads started with QThread
libpng warning: iCCP: known incorrect sRGB profile
Error
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/rare/components/tabs/settings/widgets/env_vars.py", line 61, in import_env_vars
    trash_icon.setIcon(qtawesome.icon("mdi.delete"))
  File "/usr/lib/python3/dist-packages/qtawesome/__init__.py", line 125, in icon
    return _instance().icon(*names, **kwargs)
  File "/usr/lib/python3/dist-packages/qtawesome/iconic_font.py", line 259, in icon
    parsed_options.append(self._parse_options(specific_options,
  File "/usr/lib/python3/dist-packages/qtawesome/iconic_font.py", line 308, in _parse_options
    prefix, chars = self._get_prefix_chars(names)
  File "/usr/lib/python3/dist-packages/qtawesome/iconic_font.py", line 342, in _get_prefix_chars
    raise Exception(error)
Exception: Invalid font prefix "mdi"

The above exception was the direct cause of the following exception:

SystemError: <class 'PyQt5.QtCore.Qt.Orientation'> returned a result with an error set

The above exception was the direct cause of the following exception:

SystemError: <class 'PyQt5.QtCore.Qt.Orientation'> returned a result with an error set

The above exception was the direct cause of the following exception:

SystemError: <class 'PyQt5.QtCore.Qt.Orientation'> returned a result with an error set

The above exception was the direct cause of the following exception:

SystemError: <class 'PyQt5.QtCore.Qt.Orientation'> returned a result with an error set

The above exception was the direct cause of the following exception:

SystemError: <class 'PyQt5.QtCore.Qt.Orientation'> returned a result with an error set

The above exception was the direct cause of the following exception:

SystemError: <class 'PyQt5.QtCore.Qt.Orientation'> returned a result with an error set

The above exception was the direct cause of the following exception:

SystemError: <class 'PyQt5.QtCore.Qt.Orientation'> returned a result with an error set

The above exception was the direct cause of the following exception:

SystemError: <class 'PyQt5.QtCore.Qt.Orientation'> returned a result with an error set

The above exception was the direct cause of the following exception:

SystemError: <class 'PyQt5.QtCore.QModelIndex'> returned a result with an error set

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/rare/components/tabs/settings/widgets/ubisoft_activation.py", line 147, in show_ubi_games
    logger.error(
SystemError: <class 'PyQt5.QtCore.QModelIndex'> returned a result with an error set

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/rare/app.py", line 52, in excepthook
    QMessageBox.warning(None, "Error", tb)
SystemError: <class 'PyQt5.QtWidgets.QMessageBox.StandardButton'> returned a result with an error set

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/rare/app.py", line 200, in start_app
    self.mainwindow = MainWindow()
  File "/usr/lib/python3/dist-packages/rare/components/main_window.py", line 26, in __init__
    self.tab_widget = TabWidget(self)
  File "/usr/lib/python3/dist-packages/rare/components/tabs/__init__.py", line 45, in __init__
    self.settings = SettingsTab(self)
  File "/usr/lib/python3/dist-packages/rare/components/tabs/settings/__init__.py", line 20, in __init__
    self.addTab(DefaultGameSettings(True, self), self.tr("Default Settings"))
  File "/usr/lib/python3/dist-packages/rare/components/tabs/settings/default_game_settings.py", line 74, in __init__
    self.load_settings("default")
  File "/usr/lib/python3/dist-packages/rare/components/tabs/settings/default_game_settings.py", line 112, in load_settings
    self.env_vars.update_game(app_name)
  File "/usr/lib/python3/dist-packages/rare/components/tabs/settings/widgets/env_vars.py", line 297, in update_game
    self.import_env_vars()
  File "/usr/lib/python3/dist-packages/rare/components/tabs/settings/widgets/env_vars.py", line 61, in import_env_vars
    trash_icon.setIcon(qtawesome.icon("mdi.delete"))
  File "/usr/lib/python3/dist-packages/qtawesome/__init__.py", line 125, in icon
    return _instance().icon(*names, **kwargs)
  File "/usr/lib/python3/dist-packages/qtawesome/iconic_font.py", line 259, in icon
    parsed_options.append(self._parse_options(specific_options,
  File "/usr/lib/python3/dist-packages/qtawesome/iconic_font.py", line 308, in _parse_options
    prefix, chars = self._get_prefix_chars(names)
  File "/usr/lib/python3/dist-packages/qtawesome/iconic_font.py", line 342, in _get_prefix_chars
    raise Exception(error)
Exception: Invalid font prefix "mdi"
```

**Comment by Dummerle** [comment]
You can test the deb file from here. It fixes the error:

**Comment by ZephaniahNoah** [comment]
Is started loading. When it reached 100% this appeared.
![screenshot](https://user-images.githubusercontent.com/14168013/176368198-56f229b4-a572-48a4-8bd7-c264030b0479.png)
```
zephaniahnoah@zephaniahnoah-pc:~$ rare
QSocketNotifier: Can only be used with threads started with QThread
Error
```

**Comment by loathingKernel** [comment]
Is this issue still relevant? Does this still happen?

**Comment by loathingKernel** [comment]
Closing due to inactivity
