### ISSUE TITLE
[BUG] Can't get Rare to start

### ISSUE THREAD

**Issue by SprocketRocket23** [RareDevs/Rare#261]
**Describe the bug**
Attempting to run it causes an error. 

**Error message**
[RareApp] INFO: Launching Rare version 1.9.4
[RareApp] INFO: Operating System: Windows
[Core] INFO: Logging in...
ErrorError

[Rare] CRITICAL: Traceback (most recent call last):
  File "C:\Users\sum_4\AppData\Local\Programs\Python\Python311\Lib\site-packages\rare\utils\misc.py", line 396, in run
    result = self.core.get_save_games()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sum_4\AppData\Local\Programs\Python\Python311\Lib\site-packages\legendary\core.py", line 785, in get_save_games
    savegames = self.egs.get_user_cloud_saves(app_name, manifests=not not app_name)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sum_4\AppData\Local\Programs\Python\Python311\Lib\site-packages\legendary\api\egs.py", line 241, in get_user_cloud_saves
    user_id = self.user.get('account_id')
              ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

[Rare] CRITICAL: Traceback (most recent call last):
  File "C:\Users\sum_4\AppData\Local\Programs\Python\Python311\Lib\idlelib\run.py", line 578, in runcode
    exec(code, self.locals)
  File "C:\Users\sum_4\AppData\Local\Programs\Python\Python311\Lib\site-packages\rare\__main__.py", line 131, in <module>
    main()
  File "C:\Users\sum_4\AppData\Local\Programs\Python\Python311\Lib\site-packages\rare\__main__.py", line 106, in main
    start(args)
  File "C:\Users\sum_4\AppData\Local\Programs\Python\Python311\Lib\site-packages\rare\app.py", line 133, in start
    app = App(args)
          ^^^^^^^^^
  File "C:\Users\sum_4\AppData\Local\Programs\Python\Python311\Lib\site-packages\rare\app.py", line 74, in __init__
    self.launch_dialog.login()
  File "C:\Users\sum_4\AppData\Local\Programs\Python\Python311\Lib\site-packages\rare\components\dialogs\launch_dialog.py", line 188, in login
    if self.core.login():
       ^^^^^^^^^^^^^^^^^
  File "C:\Users\sum_4\AppData\Local\Programs\Python\Python311\Lib\site-packages\legendary\core.py", line 236, in login
    userdata = self.egs.start_session(self.lgd.userdata['refresh_token'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sum_4\AppData\Local\Programs\Python\Python311\Lib\site-packages\legendary\api\egs.py", line 128, in start_session
    self.session.headers['Authorization'] = f'bearer {j["access_token"]}'
                                                      ~^^^^^^^^^^^^^^^^
KeyError: 'access_token'

**Comment by Dummerle** [comment]
Epic now requires age verification. You can login on the epic games page and then try Rare again.
