### ISSUE TITLE
[BUG] Rare gives an error after loading.

### ISSUE THREAD

**Issue by Reuver** [RareDevs/Rare#330]
**Describe the bug**

Hi, I've just downloaded Rare, and it launches, but as soon as the game images load, it gives an error, and closes.

**To Reproduce**

Launch Rare, wait for the game images to load.

**System information**

- Arch Linux
- 6.5.9-arch2-1
- rare package from Arch User Repository
- Python 3.11.5

**Error message**

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/rare/utils/qt_requests.py", line 88, in prepare_data
    self.request_active.handle_func(data)
  File "/usr/lib/python3.11/site-packages/rare/components/tabs/settings/about.py", line 65, in update_available_finished
    self.update_lbl.setText("{} -> {}").format(__version__, latest_tag)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'format'

**Comment by loathingKernel** [comment]
Thanks, fixed. We will make a new release soon.
