### ISSUE TITLE
[BUG]  Homeworld Remastered Collection - Launcher Crashing

### ISSUE THREAD

**Issue by Zetta1Reid0** [RareDevs/Rare#376]
Platform : Windows 10
Rare Version : 1.10.11

Crash is not persistent. Sometimes the launcher opens / Sometimes it does not.

What I get from console :

```
Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Epic.OnlineServices.Bindings.EOS_Platform_Tick(IntPtr handle)
   at Launcher.MainWindow.RunSteamCallbacks(Object stateInfo)
   at System.Threading.TimerQueueTimer.CallCallbackInContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.TimerQueue.AppDomainTimerCallback(Int32 id)
Application "Homeworld Remastered Collection" finished with "Process crashed"
Application "dcfccf8d965a4f2281dddf9fead042de" finished with "0"
```

Full Log :

```
[RareLauncher] INFO: Launching Rare version 1.10.11
[RareLauncher] INFO: Operating System: Windows
[LGDLFS] INFO: Using Rare's LGDLFS monkey
[Core] INFO: Using Rare's LegendaryCore monkey
[Core] INFO: Using config in C:\Users\ZR/.config/legendary
[RareLauncher] INFO: Your language is not supported
[Core] INFO: Trying to re-use existing login session...
[PreLaunchThread] INFO: Sync action: None
[PreLaunchThread] INFO: No sync action
[Core] INFO: Getting authentication token...
[RareLauncher] INFO: New connection
[RareLauncher] WARNING: Process crashed
[RareLauncher] INFO: Stopping server
[RareLauncher] INFO: Server disconnected
[RareLauncher] INFO: Launching Rare version 1.10.11
[RareLauncher] INFO: Operating System: Windows
[LGDLFS] INFO: Using Rare's LGDLFS monkey
[Core] INFO: Using Rare's LegendaryCore monkey
[Core] INFO: Using config in C:\Users\ZR/.config/legendary
[RareLauncher] INFO: Your language is not supported
[Core] INFO: Trying to re-use existing login session...
[PreLaunchThread] INFO: Sync action: None
[PreLaunchThread] INFO: No sync action
[Core] INFO: Getting authentication token...
[RareLauncher] INFO: New connection
[RareLauncher] WARNING: Process crashed
[RareLauncher] INFO: Stopping server
[RareLauncher] INFO: Server disconnected
```

**Comment by loathingKernel** [comment]
This looks to me like a crash of the launcher, rather than Rare. Unless the crash is related to us attaching to its process, this most likely is not due to Rare. Can you try and see if it crashes with legendary? Legendary doesn't try to attach ot the process like we do.

**Comment by Zetta1Reid0** [comment]
Yeah with Legendary 0.20.34 (latest release) it launches every time, no crashing.

**Comment by loathingKernel** [comment]
Looking at the error again, it correlates to the issue being that we attach to the process. Maybe we should not be doing that on Windows, since it is not important to have a log of the execution. For now I will add an exception.

**Comment by Zetta1Reid0** [comment]
I forgot to ,mention that the game has it's own launcher since it is a collection , thus attaching to it is kinda pointless since it forks 1 of the 3 games and closes after that anyway.
